### ISSUE TITLE
Sincronia do onPut persistente em caso de falhas

### ISSUE THREAD

**Issue by joaohencke** [shift-code/shift.storage#7]
Hoje no Storage, quando a promessa do método registrado (onPut) é rejeitada, a tarefa executa até a mesma ser resolvida ou, se tentou até a quantidade de vezes parametrizada.

O problema é que, quando falha várias vezes, o registro ainda consta no banco de dados. 
Acredito que deva ser feito um delete do banco da entidade (caso o entidade seja persistente), porque o dado ali contido, nao será "real".

Ou devemos deixar isso a ser tratado na hora da implementaçao do callback de erro?

```javascript
if (triedTimes < syncRetries) {
   return run();
}
pendingOps.put.remove(`${prevId}-${taskData.ts}`);
if (syncMethods[taskData.methodName].onPut.errCallback) 
  syncMethods[taskData.methodName].onPut.errCallback(err);
}
```

**Comment by cainaf** [comment]
#9
